services:
  authz:
    url: ${BUNDLE_URL}
    credentials:
      plugin: auth_plugin

bundles:
  authz:
    service: authz
    resource: ${RESOURCE_PATH}

plugins:
  auth_plugin:
    auth_url: ${AUTH_URL}
    refresh_url: ${REFRESH_URL}
    assignment_url: ${ASSIGNMENT_SERVICE_URL}
    login: ${SERVICE_LOGIN}
    password: ${SERVICE_PASSWORD}
    ca_path: ${CA_PATH}
    cert_path: ${CERT_PATH}
    key_path: ${KEY_PATH}
  envoy_ext_authz_grpc:
    addr: :9191
    path: istio/authz/allow

decision_logs:
  console: true