version: '3'

services:
  opa:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8181:8181"
    environment:
      BUNDLE_URL: ${BUNDLE_URL}
      AUTH_URL: ${AUTH_URL}
      REFRESH_URL: ${REFRESH_URL}
      ASSIGNMENT_SERVICE_URL: ${ASSIGNMENT_SERVICE_URL}
      RESOURCE_PATH: ${RESOURCE_PATH}
      SERVICE_LOGIN: ${SERVICE_LOGIN}
      SERVICE_PASSWORD: ${SERVICE_PASSWORD}
      CA_PATH: ${CA_PATH}
      CERT_PATH: ${CERT_PATH}
      KEY_PATH: ${KEY_PATH}
    volumes:
      - ./config.yml:/usr/local/bin/config.yml
      - ./.cert/:/usr/local/bin/cert
    entrypoint: [ '/bin/sh', '-c' ]
    command: |
      "
      opa run --server -l debug --log-format json-pretty -c /usr/local/bin/config.yml --diagnostic-addr=0.0.0.0:8282 --disable-telemetry
      "